---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: sealed-argo
spec:
  encryptedData:
    password: AgCxe+N1KkCBX/JNllJ/z5oMDW5Nf+dW9mPjiqMWiKiePBISkBpMtamQeotqU5kyxc5Sd5bisQ4ukARj593ddHJICjGfENC1J5ooVnMyYEhXINEeLQ53oIuaWDoTJ+idG6Bt4N8PPoUSfwTfOA0b/NQlzt7lKmOEIPtCK/m7aDzBRVzkbz886bHpZ99RorQeZVpgn7/N0jla6JwPdbd3CEcgvFHVlVQaKn4ZU3ig8Hk+Un47Vu3MY0QR7u3mC/ZhJhhEALTI2IFmI9UXbgmCMQeoybYP4F3KSXwL4DkzwUHlbJC7/lVtldGtFQqdXveqm1QeL3mCVtk9uzycXXSfYHuaW+mZZ2Zxi2nZrWSAmo9wsTGTr0idkWYDbWm3ctBt0VrOGI1rMO+ZOGCvuu5RIgsR8gEi1cIUOBnJoHGTgW3Hnvp7gAPjgHfFE4oeXI5eRQV+vAnXo38jzIfv187HVIGuOY7lJOmrE0bzugk5xEvRiZbkcDNwHkQPfIx+0e6yjyTSuQHDWfyHrvIzqGSNKuX0pZV5+1XKII0FBAqpvjrjNxR4wz30TC+gaNwvXuR72cYb3Lt2rFI8k3JoDke0PrjHBZ5bKhyHOXNy2tAidxm5IDLSb5qt1naB61SBU+gVitcMIZ7tbAA6PXTSRfnha6/vWdkPXTpMDaFA2VbSAr0EkTGeAOlCSa6L6m+CB8D6NhJlMJH1JPP2bg==
    username: AgCelPy35gmxP7x7U1NziCoJRw+bSalRZVFcb7xpzxWjKDnix4A36+37wazd0FSO94iuGo2NRnkERnuq/r5qzT+VnSUaPE04TN9I21ywBI9Nv0cGzP20GuYGgRZTVZucUIKcS2XVuJOs/EOY975aOL6+XU2QP+0LZTD4CoKvGPIBJEK1vg3Lls+g7oDb7hziQB+RVCbhe5gSvf9dAHWML145n88hWtPTg/YnsMt3xSrBQLIeZoWb3Kk/2SU33oLqIZWbS0I1ytml5fxzkgDNksHGC+wNVw872GzAKsMTMV+VBDA0CIviqFURiDZxsfy5wpHJoThv5A3DUUzatmvgzXV6GNf7jAb76yPZBLi3We6RvWhSNuOo6rnF8hGGIyoJiPDJe29c6Ti62XVHgQJOv5afJWSdHGwo1h5w52ne21t/xyLPb6BnrPCZaJL7jSQxlMb//YRZ/hrnEmmQLwAGOrDHVcKdjKM/wkSVLGmWaYDTIxZCP/sYoJG3h0TrSJ5SJVCbd2RXR9SdFqnA1sOQ4jPTXgahGrjs2+kRKw8w2+WiIQPBmKFzOa0Gvxt7zKuwETvPODEvSBwj66ArPmx/shoWImljvh2J+ApJpiivq8l0g0q2G1R+giIDiRNO+cL3aD3aVhTfGfTAMuBMjhyx+mv5SY3UZJPNOBwp3a2aye4ecCwNNjv1QBRX/vpxaPWVOILWzSaDn6W+XA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: sealed-argo
